# Generated by Django 5.1.2 on 2024-10-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('canceled', 'Qaytarilgan'), ('done', 'Tasdiqlangan'), ('waiting', 'Kutilmoqda')], default='waiting', max_length=128),
        ),
    ]
